version: "3.8"
services:
  backend:
    image: phamvantien/phone-be:latest
    container_name: phone-backend
    restart: always
    environment:
      - DB_URL=mongodb://mongo-db:27017/crud_products
    depends_on:
      - mongo-db
    networks:
      - app-network

  frontend:
    image: phamvantien/phone-fe:latest
    container_name: phone-frontend
    restart: always
    ports:
      - "80:80" # Mở port 80 cho người dùng truy cập
    depends_on:
      - backend
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    container_name: phone-mongo
    restart: always
    volumes:
      - mongo_data:/data/db # Lưu dữ liệu ra ổ cứng để không mất khi restart
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
